# Пример структуры, которая должна формироваться по результатам заполнения пользователем анкеты на сайте
# приведена в формате YAML, потому что в JSON формате недопустимы комментарии, а так ограничений по формату особо нет
# обязательные к заполнению поля помечены в комментариях
# остальные поля должны быть по умолчанию либо пустыми (для строковых и числовых полей)
# либо иметь те значения, какие они имеют в этом файле (для полей типа bool)

job_title: Программист Python  # Должность (обязательное поле, должно совпадать с названием одного из резюме на сайте hh.ru)

keywords:  Программист # Ключевые слова для поиска (список через запятую)

search_field:  # Искать только
  name: true  # в названии вакансии
  company_name: true  # в названии компании
  description: true  # в описании вакансии

words_to_exclude: Google, Meta  # Исключить слова (список через запятую)

professional_role: Программист  # Специализация

industry: Финансовые услуги  # Отрасль компании

area:  Москва, Санкт-Петербург  # Регионы (список через запятую)

districts: Северное Бутово, Замоскворечье, Чертаново  # Районы (список через запятую) - есть в интерфейсе, но по факту не участвует в поиске вакансий

salary: 300000  # Уровень дохода (целое число)

only_with_salary: False  # Показывать только вакансии с указанным уровнем дохода

currency:  # Валюта (может принимать только одно значение true)
  RUR: false  # рубль
  EUR: true  # евро
  USD: false  # доллар

education:  # Образование - есть в интерфейсе, но по факту не участвует в поиске вакансий
  not_needed: true  # Не требуется или не указано
  middle: true  # Среднее профессиональное
  higher: true  # Высшее

experience: # Требуемый опыт работы (может принимать только одно значение true)
  doesntMatter: false  # Не имеет значения
  noExperience: false  # Нет опыта
  between1And3: false  # От 1 года до 3 лет
  between3And6: false  # От 3 до 6 лет
  moreThan6: true  # Более 6 лет

employment:  # Тип занятости
  FULL: true  # Полная занятость
  PART: true  # Частичная занятость
  PROJECT: true  # Проектная работа/разовое задание
  FLY_IN_FLY_OUT: true  # Вахта
  ACCEPT_TEMPORARY: true  # Оформление по ГПХ или по совместительству
  INTERNSHIP: true  # Стажировка 

job_format:  # Формат работы
  ON_SITE: true  # На месте работодателя
  REMOTE: true  # Удаленно
  HYBRID: true  # Гибрид
  FIELD_WORK: true  # Разъездной

vacancy_label:  # Другие параметры
  with_address: true  # С адресом
  accept_handicapped: true  # Доступные людям с инвалидностью
  not_from_agency: true  # Без вакансий от кадровых агентств
  accept_kids: true  # Доступные с 14 лет
  accredited_it: true  # От аккредитованных ИТ-компаний
  low_performance: true  # Меньше 10 откликов
  accept_teens: true  # Доступные с 16 лет

order_by:  # Сортировать выдачу (может принимать только одно значение true)
  relevance: true  # по соответствию
  publication_time: false  # по дате изменения
  salary_desc: false  # по убыванию зарплаты
  salary_asc: false  # по возрастанию зарплаты

period:  # Выводить (может принимать только одно значение true)
  all_time: false  # за всё время
  month: true  # за месяц
  week: false  # за неделю
  three_days: false  # за последние три дня
  one_day: false  # за сутки

show: # Количество вакансий, которые будут отображаться на одной странице (может принимать только одно значение true)
  show_20: true
  show_50: false
  show_100: false


job_blacklist: Google, Meta  # Список компаний, на вакансии которых не откликаемся (через запятую)

# Если это поле не пусто - приложение будет использовать одно готовое сопроводительное письмо
# для всех вакансий вместо генерирации отдельного сопроводительного письма для каждой вакансии
# по умолчанию это поле должно быть пустым
cover_letter: |
  Здравствуйте! Прошу рассмотреть моё резюме на роль разработчика Python в вашу компанию.

  Кратко о себе:
  - опыт работы: 4 года
  - ожидания по зарплате: от 200000 до 400000 руб
  - основной стек: Python, SQL, Django, React, REST API, Redis
  - есть опыт работы с Docker/Docker Compose
  - знаком с Airflow, FastAPI, Flask
  - проекты веду в git

  тг для связи: greg95

apply_once_at_company: true  # подаваться в каждой компании не более чем на одну вакансию (иначе можно сразу на несколько)

skip_companies_with_test: false # пропускать вакансии, которые предлагают тестовые задания

max_applies_num: 200  # максимальное число откликов за один запуск приложения, по умолчанию 200 (обязательное поле)

max_total_applies_num: 1500 # максимальное общее число откликов за все запуски приложения, по умолчанию выключено
